config/routes.rb
Rails.application.routes.draw do

  #
  # Shoppe admin interface
  #
  mount Shoppe::Engine => "/shoppe"
  
  #
  # Product browising
  #
  get 'products' => 'products#categories', :as => 'catalogue'
  get 'products/filter' => 'products#filter', :as => 'product_filter'
  get 'products/:category_id' => 'products#index', :as => 'products'
  get 'products/:category_id/:product_id' => 'products#show', :as => 'product'
  post 'products/:category_id/:product_id/buy' => 'products#add_to_basket', :as => 'buy_product'
  
  #
  # Order status
  #
  get 'order/:token' => 'orders#status', :as => 'order_status'

  #
  # Basket
  #
  get 'basket' => 'orders#show', :as => 'basket'
  delete 'basket' => 'orders#destroy', :as => 'empty_basket'
  post 'basket/:order_item_id' => 'orders#change_item_quantity', :as => 'adjust_basket_item_quantity'
  delete 'basket/:order_item_id' => 'orders#change_item_quantity'
  delete 'basket/delete/:order_item_id' => 'orders#remove_item', :as => 'remove_basket_item'
  
  #
  # Checkout
  #
  match 'checkout' => 'orders#checkout', :as => 'checkout', :via => [:get, :patch]
  match 'checkout/delivery' => 'orders#change_delivery_service', :as => 'change_delivery_service', :via => [:post]
  match 'checkout/pay' => 'orders#payment', :as => 'checkout_payment', :via => [:get, :patch]
  match 'checkout/confirm' => 'orders#confirmation', :as => 'checkout_confirmation', :via => [:get, :patch]
  
  #
  # Static pages
  #
  get ':action', :controller => 'pages', :as => 'page'
  
  # 
  # Homepage
  #
  root :to => 'pages#home'
  
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title #{@page_title} - #{Shoppe.settings.store_name}
    = stylesheet_link_tag :application
    = javascript_include_tag :application
    = csrf_meta_tags
    <link href='http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    = yield :head
  %body
    
  
    = display_flash
    
    / The main header displayed on all pages
    / Sometimes will be shorted as the page content dictates. 
    %header.main{:class => @full_header ? 'full' : 'basic'}
      .inner
        / Primary navigation
        %nav.main
          %ul
            %li= link_to "Home", root_path, :nav_item => :home
            %li
              = link_to "Our catalogue", catalogue_path, :nav_item => :catalogue, :class => 'noborder'
              %ul
                - for category in Shoppe::ProductCategory.ordered
                  %li= link_to category.name, products_path(category.permalink)
            %li= link_to "Why shop with us?", page_path(:why), :nav_item => :why
            %li= link_to "FAQs", page_path(:faqs), :nav_item => :faqs
          %h1= link_to Shoppe.settings.store_name, root_path
        
        - if @full_header
          %h2 Welcome to <em>Bosley Marco</em>.
          %p.intro Internationally Recognised Designer Brands, Delivered Straight To Your Door. (Only USA)
      
      - if @full_header
        .bar
          .inner
            
            %p.offer <b>This week only!</b> FREE next day shipping on all orders over $50.
    
    
    / Main content section
    %section.content
      .inner
      
        / Sidebar
        %section.sidebar
          - if content_for?(:sidebar)
            = yield :sidebar
          - else
            = render 'shared/basket'
            = render 'shared/reasons'
      
        / Primary section
        %section.primary
          = yield
      
    / Footer
    %footer.main
      .inner
      
        / Useful footer links (policies etc...)
        %ul.links
          
          %li= link_to "Returns policy", page_path(:returns)
          %li= link_to "Frequently asked questions", page_path(:faqs)
      
        .callUs
          %p Got any questions?
          %p marco@bosleymarco.biz
          %p 9am to 5pm, Monday to Friday.. I try to reply ASAP
          
      
      
           
            
          